FROM node:20-alpine

WORKDIR /app

# Install Chromium and dependencies for Puppeteer
# udev and ttf-freefont are crucial for avoiding crashes
# ffmpeg added for better media support
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn \
      udev \
      git \
      ffmpeg

# Tell Puppeteer to skip downloading Chrome. We will use the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "start"]